In [4]:
"""试图使用py把.mat文件转化成为.csv文件"""
import pandas as pd
inoutput2017  = pd.read_csv('data/inoutput2017.csv', header=None, names=["col_{}".format(i) for i in range(1395)])
inoutput2017

,col_0,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,...,col_1385,col_1386,col_1387,col_1388,col_1389,col_1390,col_1391,col_1392,col_1393,col_1394
0,138.885082,0.098560,0.005177,0.035672,0,0.001217,1005.626970,314.102806,145.790278,17.590364,...,0.084369,0.000829,0.000000,30.195472,0.007912,0.133330,27.594019,0.067508,0.121026,18.818487
1,0.127706,3.673717,0.033700,0.429875,0,0.016470,1.024424,0.691202,0.612962,0.006553,...,18.566070,0.334570,0.000000,0.192682,0.004213,0.021519,0.007733,0.003544,0.004922,0.357645
2,0.000000,0.065925,3.665220,0.308913,0,0.005749,0.000000,0.000000,0.000000,0.000000,...,42.519536,161.824542,0.000000,0.000000,0.000000,0.003354,0.000000,0.000000,0.000000,0.498994
3,0.000000,0.000000,0.000000,1454.298061,0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.133158
4,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1390,311.398408,31.239088,17.568997,96.350922,0,2.438299,842.182486,729.674783,332.490369,58.219815,...,2578.455836,298.752879,32.481980,23687.653631,10032.243545,30106.997904,2085.969395,2531.093040,410.334275,28747.314345
1391,12.099818,1.952084,3.126842,11.013432,0,0.213104,35.816920,63.516616,39.106928,7.080354,...,144.244695,11.873721,5.354376,1665.506218,278.784704,1442.777902,47.511526,1625.051754,119.170566,7328.555517
1392,242.997182,85.203747,96.047234,104.474189,0,3.212337,186.903851,138.404008,177.599234,11.591271,...,2169.517333,152.026934,65.703937,9506.274400,2157.865983,9827.145874,201.323323,3942.612409,3267.960707,7446.208705
1393,0.102518,0.444501,0.421690,0.007656,0,0.018144,2.133307,11.066481,1.642238,0.054122,...,4.134546,1.347504,0.577372,20.105134,1863.760328,399.890381,393.230552,2207.515072,580.628822,4688.393467
1394,323.843619,118.454685,111.187920,223.542844,0,6.109465,566.817380,1701.580225,1385.170093,88.895263,...,2122.919564,209.189503,190.308661,46327.863472,10867.125770,9465.671670,1249.914152,12207.128451,3282.149102,56083.403243